export const UsersManagerMetadata = Object.freeze({
  //  BASE_API_URL: 'http://localhost:8080/telsoft_admin_rest',
  VIEW_CREATE_FORM: {
    'display': 'form',
    'components': [
      {
        'label': 'Account',
        'components': [
          {
            'label': 'Account',
            'key': 'tab2',
            'components': [
              {
                'label': 'Columns',
                'columns': [
                  {
                    'components': [
                      {
                        'label': 'Username',
                        'allowMultipleMasks': false,
                        'showWordCount': false,
                        'showCharCount': false,
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'textfield',
                        'input': true,
                        'key': 'username',
                        'defaultValue': '',
                        'validate': {
                          'minLength': 6,
                          'pattern': '^[a-zA-Z\\d]*$',
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false,
                          'maxLength': '',
                          'minWords': '',
                          'maxWords': ''
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'widget': {
                          'type': '',
                          'format': 'yyyy-MM-dd hh:mm a',
                          'dateFormat': 'yyyy-MM-dd hh:mm a',
                          'saveAs': 'text'
                        },
                        'inputFormat': 'plain',
                        'encrypted': false,
                        'reorder': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'mask': false,
                        'inputType': 'text',
                        'inputMask': '',
                        'id': 'emf4urt'
                      },
                      {
                        'label': 'Email',
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'email',
                        'input': true,
                        'key': 'email',
                        'defaultValue': '',
                        'validate': {
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false,
                          'minLength': '',
                          'maxLength': '',
                          'minWords': '',
                          'maxWords': '',
                          'pattern': ''
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'reorder': false,
                        'encrypted': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'widget': {
                          'format': 'yyyy-MM-dd hh:mm a',
                          'dateFormat': 'yyyy-MM-dd hh:mm a',
                          'saveAs': 'text'
                        },
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'mask': false,
                        'inputType': 'email',
                        'inputMask': '',
                        'kickbox': {
                          'enabled': false
                        },
                        'id': 'ehc8mc'
                      },
                      {
                        'label': 'Address',
                        'map': {
                          'key': '',
                          'region': ''
                        },
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'address',
                        'input': true,
                        'key': 'address',
                        'defaultValue': '',
                        'validate': {
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false,
                          'minLength': '',
                          'maxLength': '',
                          'minWords': '',
                          'maxWords': '',
                          'pattern': ''
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'reorder': false,
                        'encrypted': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'widget': {
                          'format': 'yyyy-MM-dd hh:mm a',
                          'dateFormat': 'yyyy-MM-dd hh:mm a',
                          'saveAs': 'text'
                        },
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'mask': false,
                        'inputType': 'text',
                        'inputMask': '',
                        'id': 'e16mia8'
                      },
                      {
                        'label': 'Submit',
                        'state': '',
                        'theme': 'primary',
                        'shortcut': '',
                        'disableOnInvalid': true,
                        'mask': false,
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'button',
                        'key': 'submit',
                        'input': false,
                        'defaultValue': false,
                        'validate': {
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'showValidations': false,
                        'event': '',
                        'url': '',
                        'custom': '',
                        'reorder': false,
                        'encrypted': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': false,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': true,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'widget': null,
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'size': 'md',
                        'leftIcon': '',
                        'rightIcon': '',
                        'block': false,
                        'action': 'submit',
                        'id': 'eyjf36o'
                      }
                    ],
                    'width': 6,
                    'offset': 0,
                    'push': 0,
                    'pull': 0,
                    'type': 'column',
                    'input': false,
                    'hideOnChildrenHidden': false,
                    'key': 'column',
                    'tableView': true,
                    'label': 'Column',
                    'placeholder': '',
                    'prefix': '',
                    'customClass': '',
                    'suffix': '',
                    'multiple': false,
                    'defaultValue': null,
                    'protected': false,
                    'unique': false,
                    'persistent': true,
                    'hidden': false,
                    'clearOnHide': true,
                    'dataGridLabel': false,
                    'labelPosition': 'top',
                    'labelWidth': 30,
                    'labelMargin': 3,
                    'description': '',
                    'errorLabel': '',
                    'tooltip': '',
                    'hideLabel': false,
                    'tabindex': '',
                    'disabled': false,
                    'autofocus': false,
                    'dbIndex': false,
                    'customDefaultValue': '',
                    'calculateValue': '',
                    'allowCalculateOverride': false,
                    'widget': null,
                    'refreshOn': '',
                    'clearOnRefresh': false,
                    'validateOn': 'change',
                    'validate': {
                      'required': false,
                      'custom': '',
                      'customPrivate': false
                    },
                    'conditional': {
                      'show': null,
                      'when': null,
                      'eq': ''
                    },
                    'id': 'elj4slh'
                  },
                  {
                    'components': [
                      {
                        'label': 'Fullname',
                        'allowMultipleMasks': false,
                        'showWordCount': false,
                        'showCharCount': false,
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'textfield',
                        'input': true,
                        'key': 'fullname',
                        'defaultValue': '',
                        'validate': {
                          'customMessage': '',
                          'json': '',
                          'minLength': 6,
                          'required': false,
                          'custom': '',
                          'customPrivate': false,
                          'maxLength': '',
                          'minWords': '',
                          'maxWords': '',
                          'pattern': ''
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'widget': {
                          'type': '',
                          'format': 'yyyy-MM-dd hh:mm a',
                          'dateFormat': 'yyyy-MM-dd hh:mm a',
                          'saveAs': 'text'
                        },
                        'reorder': false,
                        'inputFormat': 'plain',
                        'encrypted': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'mask': false,
                        'inputType': 'text',
                        'inputMask': '',
                        'id': 'elhxtgi'
                      },
                      {
                        'label': 'Phone',
                        'allowMultipleMasks': false,
                        'showWordCount': false,
                        'showCharCount': false,
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'phoneNumber',
                        'input': true,
                        'key': 'phone',
                        'defaultValue': '',
                        'validate': {
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false,
                          'minLength': '',
                          'maxLength': '',
                          'minWords': '',
                          'maxWords': '',
                          'pattern': ''
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'reorder': false,
                        'inputFormat': 'plain',
                        'encrypted': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'widget': {
                          'format': 'yyyy-MM-dd hh:mm a',
                          'dateFormat': 'yyyy-MM-dd hh:mm a',
                          'saveAs': 'text'
                        },
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'mask': false,
                        'inputType': 'tel',
                        'inputMask': '(999) 999-9999',
                        'id': 'e8w5ft'
                      },
                      {
                        'label': 'Status',
                        'mask': false,
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'select',
                        'input': true,
                        'key': 'status',
                        'defaultValue': '',
                        'validate': {
                          'select': false,
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'data': {
                          'values': [
                            {
                              'label': 'Active',
                              'value': 'Active'
                            },
                            {
                              'label': 'Inactive',
                              'value': 'Inactive'
                            }
                          ],
                          'json': '',
                          'url': '',
                          'resource': '',
                          'custom': ''
                        },
                        'valueProperty': 'value',
                        'selectThreshold': 0.3,
                        'encrypted': false,
                        'reorder': false,
                        'lazyLoad': false,
                        'selectValues': '',
                        'disableLimit': false,
                        'sort': '',
                        'reference': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'widget': null,
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'limit': 100,
                        'dataSrc': 'values',
                        'filter': '',
                        'searchEnabled': true,
                        'searchField': '',
                        'minSearch': 0,
                        'readOnlyValue': false,
                        'authenticate': false,
                        'template': '<span>{{ item.label }}</span>',
                        'selectFields': '',
                        'searchThreshold': 0.3,
                        'fuseOptions': {},
                        'customOptions': {},
                        'id': 'epko4e9'
                      }
                    ],
                    'width': 6,
                    'offset': 0,
                    'push': 0,
                    'pull': 0,
                    'type': 'column',
                    'input': false,
                    'hideOnChildrenHidden': false,
                    'key': 'column',
                    'tableView': true,
                    'label': 'Column',
                    'placeholder': '',
                    'prefix': '',
                    'customClass': '',
                    'suffix': '',
                    'multiple': false,
                    'defaultValue': null,
                    'protected': false,
                    'unique': false,
                    'persistent': true,
                    'hidden': false,
                    'clearOnHide': true,
                    'dataGridLabel': false,
                    'labelPosition': 'top',
                    'labelWidth': 30,
                    'labelMargin': 3,
                    'description': '',
                    'errorLabel': '',
                    'tooltip': '',
                    'hideLabel': false,
                    'tabindex': '',
                    'disabled': false,
                    'autofocus': false,
                    'dbIndex': false,
                    'customDefaultValue': '',
                    'calculateValue': '',
                    'allowCalculateOverride': false,
                    'widget': null,
                    'refreshOn': '',
                    'clearOnRefresh': false,
                    'validateOn': 'change',
                    'validate': {
                      'required': false,
                      'custom': '',
                      'customPrivate': false
                    },
                    'conditional': {
                      'show': null,
                      'when': null,
                      'eq': ''
                    },
                    'id': 'ezc6jj'
                  }
                ],
                'mask': false,
                'tableView': false,
                'alwaysEnabled': false,
                'type': 'columns',
                'input': false,
                'key': 'columns2',
                'conditional': {
                  'show': '',
                  'when': '',
                  'json': '',
                  'eq': ''
                },
                'tab': 0,
                'reorder': false,
                'properties': {},
                'customConditional': '',
                'logic': [],
                'placeholder': '',
                'prefix': '',
                'customClass': '',
                'suffix': '',
                'multiple': false,
                'defaultValue': null,
                'protected': false,
                'unique': false,
                'persistent': false,
                'hidden': false,
                'clearOnHide': false,
                'dataGridLabel': false,
                'labelPosition': 'top',
                'labelWidth': 30,
                'labelMargin': 3,
                'description': '',
                'errorLabel': '',
                'tooltip': '',
                'hideLabel': false,
                'tabindex': '',
                'disabled': false,
                'autofocus': false,
                'dbIndex': false,
                'customDefaultValue': '',
                'calculateValue': '',
                'allowCalculateOverride': false,
                'widget': null,
                'refreshOn': '',
                'clearOnRefresh': false,
                'validateOn': 'change',
                'validate': {
                  'required': false,
                  'custom': '',
                  'customPrivate': false
                },
                'autoAdjust': false,
                'hideOnChildrenHidden': false,
                'id': 'eisj80j'
              }
            ]
          },
          {
            'label': 'Roles',
            'key': 'roles',
            'components': [
              {
                'type': 'custom',
                'key': 'custom2',
                'tab': 1
              }
            ]
          }
        ],
        'mask': false,
        'tableView': true,
        'alwaysEnabled': false,
        'type': 'tabs',
        'input': false,
        'key': 'account',
        'conditional': {
          'show': '',
          'when': '',
          'json': ''
        },
        'reorder': false,
        'properties': {},
        'customConditional': '',
        'logic': []
      }
    ]

  },
  VIEW_UPDATE_FORM: {
    'display': 'form',
    'components': [
      {
        'label': 'Account',
        'components': [
          {
            'label': 'Account',
            'key': 'tab2',
            'components': [
              {
                'label': 'Columns',
                'columns': [
                  {
                    'components': [
                      {
                        'label': 'Username',
                        'allowMultipleMasks': false,
                        'showWordCount': false,
                        'showCharCount': false,
                        'tableView': true,
                        'disabled': true,
                        'alwaysEnabled': false,
                        'type': 'textfield',
                        'input': true,
                        'key': 'username',
                        'defaultValue': '',
                        'validate': {
                          'minLength': 6,
                          'pattern': '^[a-zA-Z\\d]*$',
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false,
                          'maxLength': '',
                          'minWords': '',
                          'maxWords': ''
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'widget': {
                          'type': '',
                          'format': 'yyyy-MM-dd hh:mm a',
                          'dateFormat': 'yyyy-MM-dd hh:mm a',
                          'saveAs': 'text'
                        },
                        'inputFormat': 'plain',
                        'encrypted': false,
                        'reorder': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'mask': false,
                        'inputType': 'text',
                        'inputMask': '',
                        'id': 'emf4urt'
                      },
                      {
                        'label': 'Email',
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'email',
                        'input': true,
                        'key': 'email',
                        'defaultValue': '',
                        'validate': {
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false,
                          'minLength': '',
                          'maxLength': '',
                          'minWords': '',
                          'maxWords': '',
                          'pattern': ''
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'reorder': false,
                        'encrypted': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'widget': {
                          'format': 'yyyy-MM-dd hh:mm a',
                          'dateFormat': 'yyyy-MM-dd hh:mm a',
                          'saveAs': 'text'
                        },
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'mask': false,
                        'inputType': 'email',
                        'inputMask': '',
                        'kickbox': {
                          'enabled': false
                        },
                        'id': 'ehc8mc'
                      },
                      {
                        'label': 'Address',
                        'map': {
                          'key': '',
                          'region': ''
                        },
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'address',
                        'input': true,
                        'key': 'address',
                        'defaultValue': '',
                        'validate': {
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false,
                          'minLength': '',
                          'maxLength': '',
                          'minWords': '',
                          'maxWords': '',
                          'pattern': ''
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'reorder': false,
                        'encrypted': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'widget': {
                          'format': 'yyyy-MM-dd hh:mm a',
                          'dateFormat': 'yyyy-MM-dd hh:mm a',
                          'saveAs': 'text'
                        },
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'mask': false,
                        'inputType': 'text',
                        'inputMask': '',
                        'id': 'e16mia8'
                      },
                      {
                        'label': 'Submit',
                        'state': '',
                        'theme': 'primary',
                        'shortcut': '',
                        'disableOnInvalid': true,
                        'mask': false,
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'button',
                        'key': 'submit',
                        'input': false,
                        'defaultValue': false,
                        'validate': {
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'showValidations': false,
                        'event': '',
                        'url': '',
                        'custom': '',
                        'reorder': false,
                        'encrypted': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': false,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': true,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'widget': null,
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'size': 'md',
                        'leftIcon': '',
                        'rightIcon': '',
                        'block': false,
                        'action': 'submit',
                        'id': 'eyjf36o'
                      }
                    ],
                    'width': 6,
                    'offset': 0,
                    'push': 0,
                    'pull': 0,
                    'type': 'column',
                    'input': false,
                    'hideOnChildrenHidden': false,
                    'key': 'column',
                    'tableView': true,
                    'label': 'Column',
                    'placeholder': '',
                    'prefix': '',
                    'customClass': '',
                    'suffix': '',
                    'multiple': false,
                    'defaultValue': null,
                    'protected': false,
                    'unique': false,
                    'persistent': true,
                    'hidden': false,
                    'clearOnHide': true,
                    'dataGridLabel': false,
                    'labelPosition': 'top',
                    'labelWidth': 30,
                    'labelMargin': 3,
                    'description': '',
                    'errorLabel': '',
                    'tooltip': '',
                    'hideLabel': false,
                    'tabindex': '',
                    'disabled': false,
                    'autofocus': false,
                    'dbIndex': false,
                    'customDefaultValue': '',
                    'calculateValue': '',
                    'allowCalculateOverride': false,
                    'widget': null,
                    'refreshOn': '',
                    'clearOnRefresh': false,
                    'validateOn': 'change',
                    'validate': {
                      'required': false,
                      'custom': '',
                      'customPrivate': false
                    },
                    'conditional': {
                      'show': null,
                      'when': null,
                      'eq': ''
                    },
                    'id': 'elj4slh'
                  },
                  {
                    'components': [
                      {
                        'label': 'Fullname',
                        'allowMultipleMasks': false,
                        'showWordCount': false,
                        'showCharCount': false,
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'textfield',
                        'input': true,
                        'key': 'fullname',
                        'defaultValue': '',
                        'validate': {
                          'customMessage': '',
                          'json': '',
                          'minLength': 6,
                          'required': false,
                          'custom': '',
                          'customPrivate': false,
                          'maxLength': '',
                          'minWords': '',
                          'maxWords': '',
                          'pattern': ''
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'widget': {
                          'type': '',
                          'format': 'yyyy-MM-dd hh:mm a',
                          'dateFormat': 'yyyy-MM-dd hh:mm a',
                          'saveAs': 'text'
                        },
                        'reorder': false,
                        'inputFormat': 'plain',
                        'encrypted': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'mask': false,
                        'inputType': 'text',
                        'inputMask': '',
                        'id': 'elhxtgi'
                      },
                      {
                        'label': 'Phone',
                        'allowMultipleMasks': false,
                        'showWordCount': false,
                        'showCharCount': false,
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'phoneNumber',
                        'input': true,
                        'key': 'phone',
                        'defaultValue': '',
                        'validate': {
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false,
                          'minLength': '',
                          'maxLength': '',
                          'minWords': '',
                          'maxWords': '',
                          'pattern': ''
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'reorder': false,
                        'inputFormat': 'plain',
                        'encrypted': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'widget': {
                          'format': 'yyyy-MM-dd hh:mm a',
                          'dateFormat': 'yyyy-MM-dd hh:mm a',
                          'saveAs': 'text'
                        },
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'mask': false,
                        'inputType': 'tel',
                        'inputMask': '(999) 999-9999',
                        'id': 'e8w5ft'
                      },
                      {
                        'label': 'Status',
                        'mask': false,
                        'tableView': true,
                        'alwaysEnabled': false,
                        'type': 'select',
                        'input': true,
                        'key': 'status',
                        'defaultValue': '',
                        'validate': {
                          'select': false,
                          'customMessage': '',
                          'json': '',
                          'required': false,
                          'custom': '',
                          'customPrivate': false
                        },
                        'conditional': {
                          'show': '',
                          'when': '',
                          'json': '',
                          'eq': ''
                        },
                        'data': {
                          'values': [
                            {
                              'label': 'Active',
                              'value': 'Active'
                            },
                            {
                              'label': 'Inactive',
                              'value': 'Inactive'
                            }
                          ],
                          'json': '',
                          'url': '',
                          'resource': '',
                          'custom': ''
                        },
                        'valueProperty': 'value',
                        'selectThreshold': 0.3,
                        'encrypted': false,
                        'reorder': false,
                        'lazyLoad': false,
                        'selectValues': '',
                        'disableLimit': false,
                        'sort': '',
                        'reference': false,
                        'properties': {},
                        'customConditional': '',
                        'logic': [],
                        'placeholder': '',
                        'prefix': '',
                        'customClass': '',
                        'suffix': '',
                        'multiple': false,
                        'protected': false,
                        'unique': false,
                        'persistent': true,
                        'hidden': false,
                        'clearOnHide': true,
                        'dataGridLabel': false,
                        'labelPosition': 'top',
                        'labelWidth': 30,
                        'labelMargin': 3,
                        'description': '',
                        'errorLabel': '',
                        'tooltip': '',
                        'hideLabel': false,
                        'tabindex': '',
                        'disabled': false,
                        'autofocus': false,
                        'dbIndex': false,
                        'customDefaultValue': '',
                        'calculateValue': '',
                        'allowCalculateOverride': false,
                        'widget': null,
                        'refreshOn': '',
                        'clearOnRefresh': false,
                        'validateOn': 'change',
                        'limit': 100,
                        'dataSrc': 'values',
                        'filter': '',
                        'searchEnabled': true,
                        'searchField': '',
                        'minSearch': 0,
                        'readOnlyValue': false,
                        'authenticate': false,
                        'template': '<span>{{ item.label }}</span>',
                        'selectFields': '',
                        'searchThreshold': 0.3,
                        'fuseOptions': {},
                        'customOptions': {},
                        'id': 'epko4e9'
                      }
                    ],
                    'width': 6,
                    'offset': 0,
                    'push': 0,
                    'pull': 0,
                    'type': 'column',
                    'input': false,
                    'hideOnChildrenHidden': false,
                    'key': 'column',
                    'tableView': true,
                    'label': 'Column',
                    'placeholder': '',
                    'prefix': '',
                    'customClass': '',
                    'suffix': '',
                    'multiple': false,
                    'defaultValue': null,
                    'protected': false,
                    'unique': false,
                    'persistent': true,
                    'hidden': false,
                    'clearOnHide': true,
                    'dataGridLabel': false,
                    'labelPosition': 'top',
                    'labelWidth': 30,
                    'labelMargin': 3,
                    'description': '',
                    'errorLabel': '',
                    'tooltip': '',
                    'hideLabel': false,
                    'tabindex': '',
                    'disabled': false,
                    'autofocus': false,
                    'dbIndex': false,
                    'customDefaultValue': '',
                    'calculateValue': '',
                    'allowCalculateOverride': false,
                    'widget': null,
                    'refreshOn': '',
                    'clearOnRefresh': false,
                    'validateOn': 'change',
                    'validate': {
                      'required': false,
                      'custom': '',
                      'customPrivate': false
                    },
                    'conditional': {
                      'show': null,
                      'when': null,
                      'eq': ''
                    },
                    'id': 'ezc6jj'
                  }
                ],
                'mask': false,
                'tableView': false,
                'alwaysEnabled': false,
                'type': 'columns',
                'input': false,
                'key': 'columns2',
                'conditional': {
                  'show': '',
                  'when': '',
                  'json': '',
                  'eq': ''
                },
                'tab': 0,
                'reorder': false,
                'properties': {},
                'customConditional': '',
                'logic': [],
                'placeholder': '',
                'prefix': '',
                'customClass': '',
                'suffix': '',
                'multiple': false,
                'defaultValue': null,
                'protected': false,
                'unique': false,
                'persistent': false,
                'hidden': false,
                'clearOnHide': false,
                'dataGridLabel': false,
                'labelPosition': 'top',
                'labelWidth': 30,
                'labelMargin': 3,
                'description': '',
                'errorLabel': '',
                'tooltip': '',
                'hideLabel': false,
                'tabindex': '',
                'disabled': false,
                'autofocus': false,
                'dbIndex': false,
                'customDefaultValue': '',
                'calculateValue': '',
                'allowCalculateOverride': false,
                'widget': null,
                'refreshOn': '',
                'clearOnRefresh': false,
                'validateOn': 'change',
                'validate': {
                  'required': false,
                  'custom': '',
                  'customPrivate': false
                },
                'autoAdjust': false,
                'hideOnChildrenHidden': false,
                'id': 'eisj80j'
              }
            ]
          },
          {
            'label': 'Roles',
            'key': 'roles',
            'components': [
              {
                'type': 'custom',
                'key': 'custom2',
                'tab': 1
              }
            ]
          }
        ],
        'mask': false,
        'tableView': true,
        'alwaysEnabled': false,
        'type': 'tabs',
        'input': false,
        'key': 'account',
        'conditional': {
          'show': '',
          'when': '',
          'json': ''
        },
        'reorder': false,
        'properties': {},
        'customConditional': '',
        'logic': []
      }
    ]

  }, SEARCH_VIEW: {
    'display': 'form',
    'components': [
      {
        'label': 'Columns',
        'columns': [
          {
            'components': [
              {
                'label': 'Username',
                'allowMultipleMasks': false,
                'showWordCount': false,
                'showCharCount': false,
                'tableView': true,
                'alwaysEnabled': false,
                'type': 'textfield',
                'input': true,
                'key': 'username',
                'defaultValue': '',
                'validate': {
                  'customMessage': '',
                  'json': ''
                },
                'conditional': {
                  'show': '',
                  'when': '',
                  'json': ''
                },
                'widget': {
                  'type': ''
                },
                'reorder': false,
                'inputFormat': 'plain',
                'encrypted': false,
                'properties': {},
                'customConditional': '',
                'logic': []
              },
              {
                'label': 'Email',
                'tableView': true,
                'alwaysEnabled': false,
                'type': 'email',
                'input': true,
                'key': 'email',
                'defaultValue': '',
                'validate': {
                  'customMessage': '',
                  'json': ''
                },
                'conditional': {
                  'show': '',
                  'when': '',
                  'json': ''
                },
                'reorder': false,
                'encrypted': false,
                'properties': {},
                'customConditional': '',
                'logic': []
              },
              {
                'label': 'Search',
                'state': '',
                'theme': 'primary',
                'shortcut': '',
                'disableOnInvalid': true,
                'mask': false,
                'tableView': true,
                'alwaysEnabled': false,
                'type': 'button',
                'key': 'submit',
                'input': true,
                'defaultValue': false,
                'validate': {
                  'customMessage': '',
                  'json': ''
                },
                'conditional': {
                  'show': '',
                  'when': '',
                  'json': ''
                },
                'showValidations': false,
                'event': '',
                'url': '',
                'custom': '',
                'reorder': false,
                'encrypted': false,
                'properties': {},
                'customConditional': '',
                'logic': []
              }
            ],
            'width': 4,
            'offset': 0,
            'push': 0,
            'pull': 0,
            'type': 'column',
            'input': false,
            'hideOnChildrenHidden': false,
            'key': 'column',
            'tableView': true,
            'label': 'Column'
          },
          {
            'components': [
              {
                'label': 'Fullname',
                'allowMultipleMasks': false,
                'showWordCount': false,
                'showCharCount': false,
                'tableView': true,
                'alwaysEnabled': false,
                'type': 'textfield',
                'input': true,
                'key': 'fullname',
                'defaultValue': '',
                'validate': {
                  'customMessage': '',
                  'json': ''
                },
                'conditional': {
                  'show': '',
                  'when': '',
                  'json': ''
                },
                'widget': {
                  'type': ''
                },
                'reorder': false,
                'inputFormat': 'plain',
                'encrypted': false,
                'properties': {},
                'customConditional': '',
                'logic': []
              },
              {
                'label': 'Status',
                'mask': false,
                'tableView': true,
                'alwaysEnabled': false,
                'type': 'select',
                'input': true,
                'key': 'status',
                'defaultValue': '',
                'validate': {
                  'customMessage': '',
                  'json': '',
                  'select': false
                },
                'conditional': {
                  'show': '',
                  'when': '',
                  'json': ''
                },
                'data': {
                  'values': [
                    {
                      'label': 'Active',
                      'value': 'Active'
                    },
                    {
                      'label': 'Inactive',
                      'value': 'Inactive'
                    }
                  ]
                },
                'valueProperty': 'value',
                'selectThreshold': 0.3,
                'encrypted': false,
                'reorder': false,
                'lazyLoad': false,
                'selectValues': '',
                'disableLimit': false,
                'sort': '',
                'reference': false,
                'properties': {},
                'customConditional': '',
                'logic': []
              }
            ],
            'width': 4,
            'offset': 0,
            'push': 0,
            'pull': 0,
            'type': 'column',
            'input': false,
            'hideOnChildrenHidden': false,
            'key': 'column',
            'tableView': true,
            'label': 'Column'
          },
          {
            'width': 4,
            'offset': 0,
            'push': 0,
            'pull': 0,
            'type': 'column',
            'input': false,
            'hideOnChildrenHidden': false,
            'key': 'column',
            'tableView': true,
            'label': 'Column',
            'components': [
              {
                'label': 'Phone',
                'allowMultipleMasks': false,
                'showWordCount': false,
                'showCharCount': false,
                'tableView': true,
                'alwaysEnabled': false,
                'type': 'phoneNumber',
                'input': true,
                'key': 'phone',
                'defaultValue': '',
                'validate': {
                  'customMessage': '',
                  'json': ''
                },
                'conditional': {
                  'show': '',
                  'when': '',
                  'json': ''
                },
                'reorder': false,
                'inputFormat': 'plain',
                'encrypted': false,
                'properties': {},
                'customConditional': '',
                'logic': []
              }
            ]
          }
        ],
        'mask': false,
        'tableView': false,
        'alwaysEnabled': false,
        'type': 'columns',
        'input': false,
        'key': 'columns2',
        'conditional': {
          'show': '',
          'when': '',
          'json': ''
        },
        'reorder': false,
        'properties': {},
        'customConditional': '',
        'logic': []
      }
    ],
    'settings': {
      'pdf': {
        'id': '1ec0f8ee-6685-5d98-a847-26f67b67d6f0',
        'src': 'https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0'
      }
    }
  }
});

